def generate_insert_sql(product_data):
    sql_template = """WITH product_row AS (
        INSERT INTO products(
            name, 
            price, 
            stock_count, 
            available_stock_count, 
            short_description, 
            long_description,
            avg_rating, 
            rating_count, 
            img_link, 
            category_id
        ) VALUES 
            (
                '{name}', 
                {price}, 
                {stock_count}, 
                {available_stock_count}, 
                '{short_description}', 
                '{long_description}',
                {avg_rating}, 
                {rating_count}, 
                '{img_link}', 
                {category_id}
            )
        RETURNING id
    )
    INSERT INTO product_categories(product_id, category_id)
    VALUES
        ((SELECT id FROM product_row), {category_id});"""
    sql = sql_template.format(**product_data)
    sql = sql.replace('"', "'")
    return sql

product_info = [
  {
    "name": "Harry Potter",
    "price": 10.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Books - Harry Porter 8 books",
    "long_description": "arry Potter is a famous pillow book series for children and adults around the world. Therefore, it is very worthy of being in your precious book collection!",
    "avg_rating": 4.7,
    "rating_count": 40,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lo2fkkf8a0313b",
    "category_id": 1
  },
  {
    "name": "Great Writing",
    "price": 10.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Great Writing Fifth Edition (2019 Edition - latest version)",
    "long_description": "As of now (April 2021), this is the 5th version - the latest version of this famous Great Writing book series. The book includes 6 levels.As of now (April 2021), this is the 5th version - the latest version of this famous Great Writing book series. The book includes 6 levels.\nThis is a very good set of self-study books. At the beginning of each lesson, there is a grammar for writing section used in the lesson, and a Writer\" Note and practice section after each instruction. There is an Example paragraph section that explains words in the reading comprehension lesson to learn vocabulary in the best way.",
    "avg_rating": 4.6,
    "rating_count": 40,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lo3rx5mx3njhda",
    "category_id": 1
  },
  {
    "name": "Doraemon",
    "price": 9.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "DOREMON 24 BOOKS - ENGLISH - LONG STORY",
    "long_description": "DOREMON 24 BOOKS - ENGLISH - LONG STORY",
    "avg_rating": 4.9,
    "rating_count": 50,
    "img_link": "https://down-vn.img.susercontent.com/file/sg-11134201-7rd40-lut3jtjy5giib3",
    "category_id": 1
  },
  {
    "name": "The Great Gatsby",
    "price": 10.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "A classic novel by F. Scott Fitzgerald",
    "long_description": "The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, near New York City, the novel depicts first-person narrator Nick Carraway''s interactions with mysterious millionaire Jay Gatsby and Gatsby''s obsession to reunite with his former lover, Daisy Buchanan.",
    "avg_rating": 4.8,
    "rating_count": 50,
    "img_link": "https://img.upanh.tv/2024/06/08/81QuEGw8VPL._AC_UF10001000_QL80_.jpg",
    "category_id": 1
  },
  {
    "name": "Dac Nhan Tam",
    "price": 11.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Personal development books",
    "long_description": "Famous book about personal development and communication",
    "avg_rating": 5,
    "rating_count": 50,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lp267r3nv61a6c",
    "category_id": 1
  },
  {
    "name": "Inception",
    "price": 14.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "A mind-bending thriller by Christopher Nolan",
    "long_description": "Dom Cobb is a thief with the rare ability to enter people''s dreams and steal their secrets from their subconscious. His skill has made him a hot commodity in the world of corporate espionage but has also cost him everything he loves. Cobb gets a chance at redemption when he is offered a seemingly impossible task: Plant an idea in someone''s mind.",
    "avg_rating": 4.6,
    "rating_count": 70,
    "img_link": "https://img.upanh.tv/2024/06/08/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw._V1_.jpg",
    "category_id": 2
  },
  {
    "name": "Avengers: Infinity War",
    "price": 49.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Superhero movie",
    "long_description": "Famous superhero movie from Marvel Studios",
    "avg_rating": 4.5,
    "rating_count": 50,
    "img_link": "https://img.upanh.tv/2024/06/09/image355e3f6bc3b1a27c.png",
    "category_id": 2
  },
  {
    "name": "Forrest Gump",
    "price": 50,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Classic film",
    "long_description": "Classic filmFamous superhero movie from Marvel Studios",
    "avg_rating": 4.7,
    "rating_count": 40,
    "img_link": "https://img.upanh.tv/2024/06/09/image19527c8f0a25bb7f.png",
    "category_id": 2
  },
  {
    "name": "Tesla Model S",
    "price": 99.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "An electric vehicle by Tesla",
    "long_description": "The Tesla Model S is an all-electric five-door liftback sedan produced by Tesla, Inc. It was introduced on June 22, 2012. As of August 2020, the Model S Long Range Plus has an EPA range of 402 miles (647 km), higher than that of any other battery electric car.",
    "avg_rating": 4.9,
    "rating_count": 70,
    "img_link": "https://img.upanh.tv/2024/06/08/2018_Tesla_Model_S_75D.jpg",
    "category_id": 2
  },
  {
    "name": "Honda Wave motorbike",
    "price": 88.88,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Motorcycles save fuel",
    "long_description": "Honda Wave motorbike with compact design and fuel economy",
    "avg_rating": 4.4,
    "rating_count": 60,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lun8fcfgb09xb8",
    "category_id": 2
  },
  {
    "name": "Toyota Corolla",
    "price": 99.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Popular sedans",
    "long_description": "One of Toyota\"s popular and reliable sedan models.",
    "avg_rating": 4.9,
    "rating_count": 80,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-50009109-fac1952b051897f9aaec3a41203e1fcb",
    "category_id": 2
  },
  {
    "name": "Sport bicycle",
    "price": 70.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Mountain bike",
    "long_description": "Strong and durable off-road sports bike",
    "avg_rating": 4.7,
    "rating_count": 30,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lto45t5zdnuyd8",
    "category_id": 2
  },
  {
    "name": "Men’s T-Shirt",
    "price": 45.77,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "A comfortable cotton t-shirt",
    "long_description": "This classic cotton t-shirt is perfect for everyday wear. Made from 100% cotton, it is both soft and breathable. Available in multiple sizes and colors.",
    "avg_rating": 4.6,
    "rating_count": 100,
    "img_link": "https://img.upanh.tv/2024/06/08/tee1.webp",
    "category_id": 3
  },
  {
    "name": "Levi Jeans",
    "price": 45.5,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Classic jeans from the Levi brand",
    "long_description": "The youthful straight-leg jeans shape creates an extremely standard form for wearers. Large pockets are very convenient for storing smart phones or large wallets.",
    "avg_rating": 4.5,
    "rating_count": 90,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lo23rrevl8199f",
    "category_id": 3
  },
  {
    "name": "Polo T-Shirts",
    "price": 30.5,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Classic T-shirt with Polo TORNO Men logo.",
    "long_description": "TORANO Men\"s Polo Shirt, breathable and comfortable, plain cotton fabric BASIC Masculine, Luxurious, Elegant TP038",
    "avg_rating": 4.4,
    "rating_count": 80,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lrxzynm5unq19e",
    "category_id": 3
  },
  {
    "name": "Ray-Ban sunglasses",
    "price": 45.6,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Fashion sunglasses",
    "long_description": "Ray-Ban sunglasses with stylish design and UV protection",
    "avg_rating": 4.3,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/788b639d0c25b534af666964e0319ff9",
    "category_id": 3
  },
  {
    "name": "Balo laptop Samsonite",
    "price": 43.5,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Shockproof backpack",
    "long_description": "Samsonite Laptop Backpack with shockproof compartment protects laptop.",
    "avg_rating": 4.1,
    "rating_count": 50,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134201-23020-d8w8cqzacunv37",
    "category_id": 3
  },
  {
    "name": "Casio G-Shock watch",
    "price": 50,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Sports watch",
    "long_description": "Casio G-Shock watches are waterproof and impact resistant",
    "avg_rating": 4.2,
    "rating_count": 30,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lia0el0xzqvm0b",
    "category_id": 3
  },
  {
    "name": "Adidas T-shirt",
    "price": 10,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Sports shirt",
    "long_description": "Adidas T-shirt with cool material and dynamic design",
    "avg_rating": 4,
    "rating_count": 50,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lusote164vfp87",
    "category_id": 3
  },
  {
    "name": "Samsonite travel suitcase",
    "price": 20.5,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Durable and beautiful travel suitcase",
    "long_description": "Samsonite travel suitcase with durable material and convenient design",
    "avg_rating": 4.3,
    "rating_count": 40,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lufv0ieu8ht146",
    "category_id": 3
  },
  {
    "name": "Calvin Klein office shirt",
    "price": 30.59,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Men\"s office shirt",
    "long_description": "Calvin Klein office shirt with cool material and luxurious design",
    "avg_rating": 4.4,
    "rating_count": 50,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134201-7r98o-lqn1nuors4s7cf",
    "category_id": 3
  },
  {
    "name": "Nike Air Max sneakers",
    "price": 45.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Stylish sneakers",
    "long_description": "Nike Air Max sneakers with a stylish and comfortable design",
    "avg_rating": 4.7,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lqsxjjdna7rmb6",
    "category_id": 3
  },
  {
    "name": "The North Face jacket",
    "price": 44.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Waterproof jacket",
    "long_description": "The North Face jacket is waterproof and keeps you warm",
    "avg_rating": 4.4,
    "rating_count": 78,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134201-7r98o-lu08mtu9ru3d29",
    "category_id": 3
  },
  {
    "name": "Gucci handbags",
    "price": 59.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Fashion handbags",
    "long_description": "High-end and fashionable Gucci handbags.",
    "avg_rating": 4.5,
    "rating_count": 90,
    "img_link": "https://down-vn.img.susercontent.com/file/th-11134207-7r98q-ln17vgmwuys386",
    "category_id": 3
  },
  {
    "name": "Unisex fashion glasses",
    "price": 49.5,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Unisex Fashion Glasses Korean Style Square Half Frame Anti-Blue Light Glasses",
    "long_description": "- The frame legs are made from flexible plastic and metal, helping to wear the glasses for a long time without causing discomfort or pain in the ear. - The frame legs are made from flexible plastic and metal, helping to wear the glasses for a long time without causing discomfort or pain in the ear.\n\n       - Frame-based glasses are 0-degree glasses that you can wear for fashion, dust protection or install close-up glasses.\n\n       - Firm frame latches help keep eyeglasses form well.\n\n       - Oval eyeglass frames are fashionably designed to suit both men and women, youthful and dynamic Korean style.",
    "avg_rating": 4.1,
    "rating_count": 45,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lmak0d83qy8v2c",
    "category_id": 3
  },
  {
    "name": "Men belts",
    "price": 45.55,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "High quality men leather belt, luxury men automatic buckle belt, black leather belt TLD01",
    "long_description": "Sophisticated and sharp, beautifully shaped and plated, creating elegance and class for an accessory that easily attracts gentlemen and is a delicate highlight for every outfit.",
    "avg_rating": 4.3,
    "rating_count": 55,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lqurugc8jd1g94",
    "category_id": 3
  },
  {
    "name": "Men\"s vest",
    "price": 33.45,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Elegant vest",
    "long_description": "Elegant and stylish men\"s suit, suitable for important events.",
    "avg_rating": 4.5,
    "rating_count": 65,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lug9owihnkeq63",
    "category_id": 3
  },
  {
    "name": "Balo Da Teelab Local Brand Essentials Leather Backpack AC085",
    "price": 55,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "You will never be younger than you are at this very moment “Enjoy Your Youth!",
    "long_description": "You will never be younger than you are at this very moment “Enjoy Your Youth!",
    "avg_rating": 4.3,
    "rating_count": 66,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lk0sgv3fm2t0b9",
    "category_id": 3
  },
  {
    "name": "Balo MLKSRH KQES",
    "price": 45,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "MLKSRH KQES backpack has large capacity, light weight, waterproof and easy to coordinate with fashion outfits",
    "long_description": "The textured printed fabric is light, comfortable to the touch, abrasion resistant and supple",
    "avg_rating": 4.1,
    "rating_count": 65,
    "img_link": "https://down-vn.img.susercontent.com/file/sg-11134201-22120-od1g8xu9xelv48",
    "category_id": 3
  },
  {
    "name": "New Men Sneakers 2024",
    "price": 44,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "New 2024 men sports shoes, breathable mesh walking shoes, anti-slip soft sole FASA STORE",
    "long_description": "Design style: New Korean trend design 2024- Upper material: PU leather combined with breathable mesh fabric\n- Sole material: Solid molded rubber sole with anti-slip texture\n- Heel height: flat heel, sole height about 3 cm\n- Color classification: Brown, Gray\n- Shoe size: 39, 40, 41, 42, 43, 44",
    "avg_rating": 4.2,
    "rating_count": 60,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lqm5869j5i5z6b",
    "category_id": 3
  },
  {
    "name": "Neutrogena sunscreen",
    "price": 45.5,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Sunscreen SPF 50",
    "long_description": "Neutrogena sunscreen with SPF 50 protects skin from UV rays",
    "avg_rating": 4.2,
    "rating_count": 67,
    "img_link": "https://down-vn.img.susercontent.com/file/fda9914210217b76c4f557d6d0b311c8",
    "category_id": 3
  },
  {
    "name": "MAC lipstick",
    "price": 55.55,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "High quality lipstick",
    "long_description": "MAC lipstick with bright and long-lasting colors.",
    "avg_rating": 4.3,
    "rating_count": 70,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134201-7r98o-lt3ro99gor6y14",
    "category_id": 3
  },
  {
    "name": "Amour Bad Boy Plus Men Perfumer",
    "price": 49.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Amour Bad Boy Plus Men Perfume French Imported Ingredients Sweet, Mysterious, Alluring Fragrance Spray 10ml and 2ml",
    "long_description": "A:MOUR - Is a local brand specializing in manufacturing and researching perfume lines with affordable prices, elegant, youthful scents with long lasting scent.",
    "avg_rating": 4.5,
    "rating_count": 70,
    "img_link": "https://down-vn.img.susercontent.com/file/sg-11134201-22120-nsdzqkhbcukv6c",
    "category_id": 3
  },
  {
    "name": "Modern Sofa",
    "price": 45.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "A stylish and comfortable sofa",
    "long_description": "This modern sofa is perfect for any living room. It features a sleek design and is upholstered in high-quality fabric. The sofa is both comfortable and durable, making it a great addition to your home.",
    "avg_rating": 4.4,
    "rating_count": 80,
    "img_link": "https://img.upanh.tv/2024/06/08/European-Luxury-Modern-Living-Room-Genuine-Leather-U-Shape-LED-Sofa.webp",
    "category_id": 4
  },
  {
    "name": "Wooden wardrobe",
    "price": 30,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Convenient wardrobe",
    "long_description": "Wooden wardrobe with convenient design and many compartments",
    "avg_rating": 4.6,
    "rating_count": 66,
    "img_link": "https://down-vn.img.susercontent.com/file/22426cb8f55de0dbb9238b00b5158e0e",
    "category_id": 4
  },
  {
    "name": "Smart study desk",
    "price": 45.65,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Multi-purpose study desk",
    "long_description": "Smart study desk with convenient design and many storage compartments",
    "avg_rating": 4.7,
    "rating_count": 65,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lifpnrvnpmh8e4",
    "category_id": 4
  },
  {
    "name": "ZingZingMart pillowcase",
    "price": 75.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "ZingZingMart pillowcase made of soft and cool poly cotton (suitable for 20cm diameter intestine)",
    "long_description": "Use it to add variety to your bedroom space or use it with your family\"s old set to make it easier to change laundry (especially when it\"s hot and humid).",
    "avg_rating": 4.6,
    "rating_count": 44,
    "img_link": "https://down-vn.img.susercontent.com/file/0f795c74231b510e6ff95b3e8f18acd4",
    "category_id": 4
  },
  {
    "name": "Wooden wardrobe",
    "price": 79.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Convenient wardrobe",
    "long_description": "Wooden wardrobe with convenient design and many compartments.",
    "avg_rating": 4.4,
    "rating_count": 65,
    "img_link": "https://down-vn.img.susercontent.com/file/22426cb8f55de0dbb9238b00b5158e0e",
    "category_id": 4
  },
  {
    "name": "Leather sofa set",
    "price": 69.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "High quality leather sofa",
    "long_description": "High quality leather sofa set with luxurious and comfortable design",
    "avg_rating": 4.5,
    "rating_count": 66,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lq6ekru0xuj624",
    "category_id": 4
  },
  {
    "name": "Smart study desk",
    "price": 79.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Multi-purpose study desk",
    "long_description": "Smart study desk with convenient design and many storage compartments",
    "avg_rating": 4.5,
    "rating_count": 66,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lifpnrvnpmh8e4",
    "category_id": 4
  },
  {
    "name": "Office swivel chair",
    "price": 85.5,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Comfortable swivel chair",
    "long_description": "Office swivel chair with soft cushion and back support design",
    "avg_rating": 5,
    "rating_count": 77,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lmeyof3jbilbe9",
    "category_id": 4
  },
  {
    "name": "Full body massage chair",
    "price": 35.78,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Relaxing massage chair",
    "long_description": "Full body massage chair with many massage modes and luxurious design",
    "avg_rating": 5,
    "rating_count": 88,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lu0d9dnbr3f56a",
    "category_id": 4
  },
  {
    "name": "Ikea wooden bookshelf",
    "price": 45.76,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Convenient bookshelf",
    "long_description": "Ikea wooden bookshelf with simple design and large storage capacity",
    "avg_rating": 5,
    "rating_count": 90,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-llm3d31ojfss9e",
    "category_id": 4
  },
  {
    "name": "Earphone Apple AirPods with Charging Case 2nd gen",
    "price": 45.66,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Earphone Apple AirPods with Charging Case 2nd gen",
    "long_description": "With optimal talk time, breakthrough technology and combined with the Charging Case, AirPods provide the ultimate wireless headset experience like never before. The headset can be used with all your devices (2). Once inserted, the headphones connect instantly, immersing you in rich, high-fidelity sound. All great.",
    "avg_rating": 5,
    "rating_count": 88,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lmd1u9d71pen39",
    "category_id": 4
  },
  {
    "name": "Mini Bluetooth Speaker",
    "price": 56.89,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "ini Bluetooth Speaker Handheld portable mini bluetooth speaker 💥Color Changing LED Light💥 - Free Charging Cord, Bluetooth 5.0 technology",
    "long_description": "ini Bluetooth Speaker Handheld portable mini bluetooth speaker 💥Color Changing LED Light💥 - Free Charging Cord, Bluetooth 5.0 technology",
    "avg_rating": 4.5,
    "rating_count": 56,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lg0cvov1tvfuc7",
    "category_id": 4
  },
  {
    "name": "HUAWEI WATCH FIT",
    "price": 56.78,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "HUAWEI WATCH FIT 3 Smart Watch Gray (Nylon Strap) | Slim and Light Design | 1.82\" AMOLED Screen | Comprehensive Workout Management | Up to 10 Days of Usage",
    "long_description": "HUAWEI WATCH FIT 3 Smart Watch Gray (Nylon Strap) | Slim and Light Design | 1.82\" AMOLED Screen | Comprehensive Workout Management | Up to 10 Days of Usage",
    "avg_rating": 4.3,
    "rating_count": 45,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lvnznrev5ri172",
    "category_id": 4
  },
  {
    "name": "Giá đỡ LAPTOP, ĐIỆN THOẠI",
    "price": 45.98,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Aluminum LAPTOP, PHONE, COMPUTER stand with adjustable height, laptop stand",
    "long_description": "The laptop stand can be adjusted to different heights, helping you relieve shoulder and waist pain, protecting your eyes, eliminating hand fatigue, and ventilation design to prevent the device from overheating.",
    "avg_rating": 4.4,
    "rating_count": 60,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lvnznrev5ri172",
    "category_id": 4
  },
  {
    "name": "Mini Handheld Massage Machine",
    "price": 90.5,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Handheld massage gun for back punching, neck and shoulder therapeutic massage, 4 heads, 6 modes, good product",
    "long_description": "Uses and Functions:Uses and Functions:\n       - Standard ball massage head: suitable for massaging large muscle forces such as waist, back, thighs...\n       -shaped massage head: used for neck and spine massage.\n       - Flat massage head: suitable for large muscle areas such as biceps, thighs, and calves\n       - Conical massage head: suitable for massaging palms, soles, heels....",
    "avg_rating": 4.3,
    "rating_count": 55,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lg5wu1a0wd8705",
    "category_id": 4
  },
  {
    "name": "Medical Gloves",
    "price": 45.88,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Powdered medical gloves, powder-free medical gloves",
    "long_description": "Powder-free medical gloves with 7-80c powder box",
    "avg_rating": 4.3,
    "rating_count": 45,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-ltz32pbw5amp63",
    "category_id": 4
  },
  {
    "name": "Samsung refrigerator",
    "price": 56.87,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Large capacity refrigerator",
    "long_description": "Samsung refrigerator with large capacity and many convenient features",
    "avg_rating": 4.3,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-loz7ji6k6mhadf",
    "category_id": 4
  },
  {
    "name": "LG Inverter washing machine",
    "price": 56.88,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Washing machine saves electricity",
    "long_description": "LG Inverter washing machine with energy saving technology and effective cleaning",
    "avg_rating": 4.3,
    "rating_count": 44,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lt7vsysz443o84",
    "category_id": 4
  },
  {
    "name": "Philips table lamp",
    "price": 56.9,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "LED table lamp",
    "long_description": "Philips table lamp with energy-saving LED light",
    "avg_rating": 4.5,
    "rating_count": 65,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134201-7r98o-lvyi4itubudod3",
    "category_id": 4
  },
  {
    "name": "Dyson vacuum cleaner",
    "price": 56.8,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Cordless vacuum cleaner",
    "long_description": "Dyson cordless vacuum cleaner with powerful suction",
    "avg_rating": 4.3,
    "rating_count": 66,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-ltnb844pvk7e40",
    "category_id": 4
  },
  {
    "name": "Nespresso coffee machine",
    "price": 45.54,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Capsule coffee maker",
    "long_description": "Nespresso coffee maker is convenient and fast",
    "avg_rating": 4.6,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-llnasdce574fa1",
    "category_id": 4
  },
  {
    "name": "Philips oil-free fryer",
    "price": 58.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Modern oil-free fryer",
    "long_description": "Philips oil-free fryer with oil-free frying technology and easy to use",
    "avg_rating": 4.5,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lw55nzre5knvf2",
    "category_id": 4
  },
  {
    "name": "Kuvings juicer",
    "price": 87.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Slow juicer",
    "long_description": "Kuvings slow juicer preserves nutrition",
    "avg_rating": 4.7,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-luyocoqtyko5fd",
    "category_id": 4
  },
  {
    "name": "Bosch induction cooker",
    "price": 76.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Induction cooker saves electricity",
    "long_description": "Bosch induction cooker with energy saving technology and quick cooking",
    "avg_rating": 4.5,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/1ecef7490e0d075d309ee75d9b72c4be",
    "category_id": 4
  },
  {
    "name": "Philips blender",
    "price": 67.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "High capacity blender",
    "long_description": "Philips blender with sharp blades and powerful motor",
    "avg_rating": 4.3,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lw55jndwll23c4",
    "category_id": 4
  },
  {
    "name": "Sony WH-1000XM4 headphones",
    "price": 67.88,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Noise-canceling headphones",
    "long_description": "Sony WH-1000XM4 headphones with advanced noise canceling technology",
    "avg_rating": 4.3,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134201-7r98o-lvx828jtj3r28c",
    "category_id": 4
  },
  {
    "name": "Canon EOS M50 camera",
    "price": 87.66,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Mirrorless camera",
    "long_description": "Canon EOS M50 camera with excellent image quality and ease of use",
    "avg_rating": 4.7,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134201-7r98o-lvmwc7h6td8oa8",
    "category_id": 4
  },
  {
    "name": "TV Samsung 55 inch",
    "price": 56.77,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "4K Smart TV",
    "long_description": "Samsung 55-inch TV with 4K resolution and smart features",
    "avg_rating": 4.6,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lr5obh6o1rbtaa",
    "category_id": 4
  },
  {
    "name": "Bose SoundLink speaker",
    "price": 78.87,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Portable Bluetooth speaker",
    "long_description": "Bose SoundLink portable Bluetooth speaker with high-quality sound",
    "avg_rating": 4.9,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/87ce851a9d5b2c29812baf0465fb06ef",
    "category_id": 4
  },
  {
    "name": "Razer mechanical keyboard",
    "price": 67.78,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Gaming keyboard",
    "long_description": "Razer mechanical keyboard for gamers with high sensitivity.",
    "avg_rating": 4.1,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lvl9vl1nw32p1a",
    "category_id": 4
  },
  {
    "name": "Canon EOS camera",
    "price": 67.87,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Professional camera",
    "long_description": "Canon EOS camera with high image quality and many features",
    "avg_rating": 4.3,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/sg-11134201-7rd4y-lw2b6wmmx3wo6a",
    "category_id": 4
  },
  {
    "name": "Tablet Samsung Galaxy Tab",
    "price": 67.87,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Android Tablet",
    "long_description": "Samsung Galaxy Tab tablet with large screen and high performance",
    "avg_rating": 4.4,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lkcsibfi19d45c",
    "category_id": 4
  },
  {
    "name": "HP LaserJet Printer",
    "price": 67.87,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Black and white laser printer",
    "long_description": "HP LaserJet printer with fast printing speed and high quality",
    "avg_rating": 4.7,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lqsvacectu7rde",
    "category_id": 4
  },
  {
    "name": "Hikvision security cameras",
    "price": 67.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "HD security cameras",
    "long_description": "Hikvision security camera with HD resolution and wireless connection",
    "avg_rating": 4.6,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lqy6m3fogb6hd6",
    "category_id": 4
  },
  {
    "name": "Everlast boxing gloves",
    "price": 87.77,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Professional boxing gloves",
    "long_description": "Everlast boxing gloves with protective padding and sturdy design",
    "avg_rating": 4.3,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/acb3f37261d846470637d20e51058e19",
    "category_id": 4
  },
  {
    "name": "Cabernet Sauvignon red wine",
    "price": 98.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Quality wine",
    "long_description": "Cabernet Sauvignon red wine from Napa Valley",
    "avg_rating": 4.7,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lkkf16ybc7hm82",
    "category_id": 4
  },
  {
    "name": "Johnnie Walker whiskey",
    "price": 88.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Premium whiskey",
    "long_description": "High quality Johnnie Walker Red Label whiskey.",
    "avg_rating": 4.8,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lvef7npr6s84ea",
    "category_id": 4
  },
  {
    "name": "Repair kit",
    "price": 78.88,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Multi-purpose tool set",
    "long_description": "Multi-purpose repair kit with many different types of tools.",
    "avg_rating": 4.4,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/5394feeb73bb1b48baf6da02fe679ec0",
    "category_id": 4
  },
  {
    "name": "Yamaha guitars",
    "price": 99.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Acoustic guitar",
    "long_description": "Yamaha acoustic guitar with warm and quality sound",
    "avg_rating": 4.7,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/5bedace211cbc47191075c751be1a11a",
    "category_id": 4
  },
  {
    "name": "Umbrella",
    "price": 23.55,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Foldable umbrella with anti-UV coating, portable outdoor sun and rain umbrella",
    "long_description": "Compact folding umbrella with eye-catching designs and colors, creating aesthetics for the user, thick Taffeta fabric, effective waterproof",
    "avg_rating": 4.6,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lsb3cmki0p1g74",
    "category_id": 4
  },
  {
    "name": "Hairdryer",
    "price": 44.33,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Modern 2-way hot and cold salon styling hair dryer with high capacity of 3500w",
    "long_description": "Hair dryer with very large design capacity of 3500w, wind speed and heat are good enough, meeting the needs of individuals and families.",
    "avg_rating": 4.3,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lnlptgcgux2le6",
    "category_id": 4
  },
  {
    "name": "Flashlight",
    "price": 23.33,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "3W Super Bright LED Flashlight (Random Color Delivery: Black/Red/Silver)",
    "long_description": "Mini flashlights like keychains, pockets...etc",
    "avg_rating": 4.4,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-50009109-0bef9fdb751252b12de4eddc032b71e3",
    "category_id": 4
  },
  {
    "name": "Battery backup",
    "price": 33.55,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Backup Battery 30000mah 2 Charging Ports - 1 Year Warranty-anhstore99",
    "long_description": "3 charging ports support Quick Charge 2.0 (Micro usb, Type C), you can use IPhone / Micro usb / Type C cable to charge this battery. Therefore, the product does not include a charging cable or charger to reduce product costs.",
    "avg_rating": 4.3,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lgg82s6m5qev32",
    "category_id": 4
  },
  {
    "name": "Xiaomi Redmi tempered glass",
    "price": 77.66,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Tempered glass Xiaomi Redmi 9D Screen Note 10/Note 9/Note 8/Note 7/Pro/Mi 11 lite/10T/9T/9C/9A/9s/",
    "long_description": "Xiaomi Redmi Tempered Glass Full 9D Screen Redmi Note 10/ Redmi note 10 pro/Mi 10t/ mi 10t pro/ mi 10t lite/ mi 11t lite/ redmi Note 9/ redmi note 9 pro/ redmi note 9s/redmi Note 8/ redmi note 8 pro/ redmi Note7/ redmi note 7 pro/ redmi 9a/ redmi 9c/ redmi 9/ redmi 9t/ redmi 8/ redmi 8a/ redmi 7/ mi 8/ mi 8 pro/ mi 9 se",
    "avg_rating": 4.5,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/e25b0bc9e706b1721ee7c6e8b45ed3fe",
    "category_id": 4
  },
  {
    "name": "Porcelain tea set",
    "price": 66.77,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Traditional tea set",
    "long_description": "Beautiful and convenient porcelain tea set for enjoying tea.",
    "avg_rating": 4.7,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lknhvez52jrk9e",
    "category_id": 4
  },
  {
    "name": "Mini Projector T9 Android 7.0",
    "price": 66.5,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Mini Projector T9 Android 7.0 Full HD 1080P,YAMAZAKI Connect Phone, innovate Movie Legend",
    "long_description": "The projector is a low-cost but impressive quality projector that can provide a great entertainment experience for watching full HD movies and listening to music.",
    "avg_rating": 4.8,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lv3269usbeux29",
    "category_id": 4
  },
  {
    "name": "Smartphone iPhone 13",
    "price": 99.77,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Smartphone",
    "long_description": "iPhone 13 phone with many modern features and great camera",
    "avg_rating": 4.9,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-50009109-1cf19d05fb4006d505c008471e5a56b7",
    "category_id": 4
  },
  {
    "name": "Laptop Dell XPS 13",
    "price": 66.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Ultra thin laptop",
    "long_description": "Dell XPS 13 laptop with powerful performance and ultra-thin design",
    "avg_rating": 4.6,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-50009109-d851329f3c4a8c69292bbb5fd791186b",
    "category_id": 4
  },
  {
    "name": "Bosch dishwasher",
    "price": 77.88,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Large capacity dishwasher",
    "long_description": "Bosch dishwasher with large capacity and many washing modes",
    "avg_rating": 4.6,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134201-7r98o-lvvzrlu3b0pka8",
    "category_id": 4
  },
  {
    "name": "Neutrogena sunscreen",
    "price": 66.77,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Sunscreen SPF 50",
    "long_description": "Neutrogena sunscreen with SPF 50 protects skin from UV rays",
    "avg_rating": 4.5,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/fda9914210217b76c4f557d6d0b311c8",
    "category_id": 4
  },
  {
    "name": "Sharp air purifier",
    "price": 55.66,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Effective air purifier",
    "long_description": "Sharp air purifier with effective dust filtering and deodorizing technology",
    "avg_rating": 4.7,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lw2u1f6bmk0r59",
    "category_id": 4
  },
  {
    "name": "PlayStation 5 gaming console",
    "price": 66.77,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "New generation game console",
    "long_description": "PlayStation 5 console with advanced graphics and smooth gaming experience",
    "avg_rating": 4.5,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lnh04gjkeewd20",
    "category_id": 4
  },
  {
    "name": "Roland electric piano",
    "price": 66.33,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Professional electric piano",
    "long_description": "Roland electric piano with high quality sound and many features",
    "avg_rating": 4.5,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lmbah99dr1svec",
    "category_id": 4
  },
  {
    "name": "LG air conditioner unit",
    "price": 33.5,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Air conditioning saves electricity",
    "long_description": "LG air conditioner with energy saving and fast cooling technology",
    "avg_rating": 4.8,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lufv2bgn75sifa",
    "category_id": 4
  },
  {
    "name": "Water purifier A.O. Smith",
    "price": 99.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Effective water purifier",
    "long_description": "Water purifier A.O. Smith with advanced water filtration technology and health protection",
    "avg_rating": 4.5,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/sg-11134201-22110-x0auum3t4ijv54",
    "category_id": 4
  },
  {
    "name": "Foreo facial cleanser",
    "price": 99.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "High-tech facial washing machine",
    "long_description": "Foreo facial cleanser with ultrasonic vibration technology and effective skin cleansing",
    "avg_rating": 4.8,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-luu7yat484rp90",
    "category_id": 4
  },
  {
    "name": "Smartwatch Apple Watch Series 9",
    "price": 99.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Latest Apple smartwatch",
    "long_description": "Apple Watch Series 9 smartwatch with larger screen and advanced health features",
    "avg_rating": 4.9,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lnau033n4tq285",
    "category_id": 4
  },
  {
    "name": "High quality chess set",
    "price": 99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Wooden chess set",
    "long_description": "Chess set made from high-quality wood with sophisticated details and luxurious chessboard",
    "avg_rating": 5,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/sg-11134201-22100-54vsx7nunbjva3",
    "category_id": 4
  },
  {
    "name": "Women\"s evening dress",
    "price": 87.5,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Luxurious evening dress",
    "long_description": "Women\"s evening dress with delicate design and soft fabric",
    "avg_rating": 4.5,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-loxh5stzzp0bbe",
    "category_id": 4
  },
  {
    "name": "Oculus Quest 2 virtual reality glasses",
    "price": 50.99,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Wireless virtual reality glasses",
    "long_description": "Oculus Quest 2 virtual reality glasses with high resolution and great gaming experience",
    "avg_rating": 4.6,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/d1dca31376411004a76c2fc38ab10cb2",
    "category_id": 4
  },
  {
    "name": "Baking tools",
    "price": 54.5,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Multi-purpose baking tool",
    "long_description": "Tefal baking tool set with many accessories and high quality materials",
    "avg_rating": 4.8,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134201-7r98o-lw82hrqyz5xaf5",
    "category_id": 4
  },
  {
    "name": "Liforme yoga mat",
    "price": 45.5,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "High quality yoga mat",
    "long_description": "Liforme yoga mat with good grip and environmentally friendly materials",
    "avg_rating": 4.2,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-ln5h0evvf4tvec",
    "category_id": 4
  },
  {
    "name": "LG TwinWash washing machine",
    "price": 99.5,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "High quality yoga mat",
    "long_description": "LG TwinWash washing machine with the ability to wash two lots of clothes at the same time and many smart washing modes",
    "avg_rating": 4.7,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-ljtn21nxxngi7c",
    "category_id": 4
  },
  {
    "name": "Dyson HP00 bladeless fan",
    "price": 65.5,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Advanced cooling fan",
    "long_description": "Dyson HP00 bladeless fan with safe design and high cooling efficiency",
    "avg_rating": 4.8,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-ltnkk34q42z13f",
    "category_id": 4
  },
  {
    "name": "Lego Star Wars set",
    "price": 45.33,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Lego toys",
    "long_description": "Lego Star Wars sets for fans",
    "avg_rating": 4.6,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lq32kb0r638208",
    "category_id": 4
  },
  {
    "name": "XINYIMEI",
    "price": 34.5,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "XINYIMEI New fashion high quality PU small square crossbody bag for men and women",
    "long_description": "We have rich experience and high-quality products, focusing on quality and low prices! Bring you the best shopping experience!",
    "avg_rating": 4.5,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/fdef7767441a48b030e9145f863da071",
    "category_id": 4
  },
  {
    "name": "Spalding Basketball",
    "price": 33.5,
    "stock_count": 50,
    "available_stock_count": 50,
    "short_description": "Professional basketball",
    "long_description": "Spalding basketball is used in professional matches",
    "avg_rating": 4.4,
    "rating_count": 100,
    "img_link": "https://down-vn.img.susercontent.com/file/sg-11134201-23010-hc2s86bywulvf2",
    "category_id": 4
  }
]
sql_commands = [generate_insert_sql(product) for product in product_info]
with open("4.insert_product.sql", "w", encoding="utf-8") as file:
    for sql_command in sql_commands:
        file.write(sql_command + "\n")